# Generated by Django 5.0.4 on 2024-04-19 14:02

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 14, 2, 18, 861109, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
